### ISSUE TITLE
SimpleWallet (WalletGreen) Atuo-Fusion needs to check available balance again

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin#114]
When sending a transaction that is too large on the new simplewallet (walletgreen) it is too aggressive in wanting to complete the operation and fails.

Need to check that the available balance is in fact available before sending the transaction and failing due to amount > available balance.
Once the balance unlocked completely I was able to send the transaction.

[fusion_however_didnt_wait_long_enough.txt](https://github.com/turtlecoin/turtlecoin/files/1840702/fusion_however_didnt_wait_long_enough.txt)

**Comment by ZedPea** [comment]
To clarify:
* You attempted to send a transaction - it was too large
* The wallet then attempted to make a fusion transaction to optimize
* This completed, and it then attempted to resend the transaction
* This failed because the balance had not completely unlocked

Is that correct?

Currently I check for all the fusion transactions to no longer be present in the unconfirmedtransactionhashes before attempting to resend - I assumed once they had left this the balance would also unlock.

I initially considered storing the locked balance, sending the transactions, and then waiting until the locked balance was less than or equal to the initial locked balance to check that they had confirmed, however this is complicated if you receive a transaction whilst the fusion is confirming - your locked balance will increase however the fusions will have completed. If you were constantly recieving payments your locked balance might never return to the original amount and you would have to force close the wallet.

I'm not sure what the best way to handle this is, other than adding a check that amount <= available balance.

Any thoughts? I will add that check now.

**Comment by ZedPea** [comment]
Actually, we can just sleep until we have enough balance to send. Assuming the user isn't sending TRTL with another wallet at the same time, this should always succeed.

**Comment by ZedPea** [comment]
Should now be fixed.

**Comment by bobbieltd** [comment]
@Zedpea What is maximum coins amount (I don’t know how to estimate transaction size without sending) to send at the moment (without fusion) ?

**Comment by ZedPea** [comment]
I don't think there is a maximum amount aside from the limits of the data type (2^64 / 100 == 184467440737095516 TRTL), because it all depends upon the amount of inputs you have.

If you received one payment of 100 million TRTL you could then send that out again and it would be a very small transaction.

However, if you received lots of small transactions of 1000 TRTL, you would only be able to send perhaps 400k TRTL without it getting stuck in the transaction pool. Currently it seems if the input amount is somewhere around the 400 amount it will get stuck. Unfortunately I'm not sure if there's a way to tell if a transaction will get stuck other than getting it's transaction size.

Currently people suggest only sending 100k at a time to ensure it will never get stuck, though I have seen one transaction of that size get stuck before.

**Comment by bobbieltd** [comment]
Thanks for info.

**Comment by SoreGums** [comment]
btw your summary was correct.

I think it will need a timeout feature though, to give up and say as such

> Fusion transactions have completed, however available balance is less than transfer amount specified. Transfer aborted, please review and start a new transfer.

are there fees involved in fusion transactions? Becomes an issue if sweeping a wallet, since the idea is to remove all funds.

**Comment by ZedPea** [comment]
Fusion transactions are 0 fee. Why do you suggest a timeout? I'm not sure what would cause them to not have enough balance after all the transactions have unlocked, as we do already check this before sending initially.

**Comment by SoreGums** [comment]
ok zero fee is fine then.
wasn't sure. was thinking for "ok what if..." that's all :)
if it isn't needed then should be fine.
looking to avoid a situation where the user is like "wtf, why can't i do anything..."

**Comment by ZedPea** [comment]
I suppose it wouldn't hurt.

**Comment by ZedPea** [comment]
Done.

**Comment by SoreGums** [comment]
still fails :/

I had a go at debugging it however the breakpoints i set kept resulting in a different exception complaining about a function needing params and if it didn't have them it would abort...
so I couldn't help narrow down the issue.

basically it is just too fast to send the transaction once the balance is available, because if I press up (windows has command history for some reason while linux/mac doesn't) and press enter and y as fast as i can, it works...

**Comment by ZedPea** [comment]
That's weird, I guess the wallet is lying to us.... Just pop a delay before sending? What kinda length delay do you think is enough, 5 seconds?

**Comment by SoreGums** [comment]
actually, scratch some of that.

was just creating a new issue about not being able to send the final 2TRTL in my wallet.
maybe this is why it can't send.
however I am not hitting the error "sorry u have dust", only the error "not enough money".

this is so hard to test properly :P

**Comment by ZedPea** [comment]
Yeah, sometimes it throws an exception when you have dust and sometimes it just says wrong amount... very helpful...

**Comment by SoreGums** [comment]
ok, got a new fusion in progress with 21TRTL left in the wallet... let's see what happens

**Comment by SoreGums** [comment]
it didn't finish fussing...
![image](https://user-images.githubusercontent.com/317/37857132-57693e62-2f2b-11e8-9361-a7abb29914c1.png)

**Comment by ZedPea** [comment]
Just checked and it seems correct - however I think it might be throwing an exception whilst checking if the transaction is too large so it skips the sleeping. If I add the sleep before checking that, hopefully it will act correctly. Have pushed up a commit.

**Comment by SoreGums** [comment]
got rid of the last balance with a mixin of 0.

finally back to an empty wallet so I don't need to create a new one.
this time I'll keep transfers above 20 to hopefully not end up with a bunch of dust.

**Comment by SoreGums** [comment]
woohoo - winner winner 🐔 🍽 

![image](https://user-images.githubusercontent.com/317/37858413-f51e4e4e-2f36-11e8-8a97-af8584ee616d.png)

auto fusion > boom. nce one!

**Comment by ZedPea** [comment]
Yay! Thanks for the great help!
