### ISSUE TITLE
pathspec 'v0.3.1' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by Svolentin** [turtlecoin/turtlecoin#33]
hi! 
trying to build latest 0.3.1

```git pull && docker build . -t turtlecoin```

```
...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
Cloning into '/src/turtlecoin'...
error: pathspec 'v0.3.1' did not match any file(s) known to git.
The command '/bin/sh -c apt-get update &&     apt-get install -y       build-essential       python-dev       gcc-4.9       g++-4.9       git cmake       libboost1.58-all-dev       librocksdb-dev &&     git clone https://github.com/turtlecoin/turtlecoin.git /src/turtlecoin &&     cd /src/turtlecoin &&     git checkout $TURTLECOIN_VERSION &&     mkdir build &&     cd build &&     cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. &&     make -j$(nproc) &&     mkdir -p /usr/local/bin &&     cp src/TurtleCoind /usr/local/bin/TurtleCoind &&     cp src/walletd /usr/local/bin/walletd &&     cp src/simplewallet /usr/local/bin/simplewallet &&     cp src/miner /usr/local/bin/miner &&     cp src/connectivity_tool /usr/local/bin/connectivity_tool &&     strip /usr/local/bin/TurtleCoind &&     strip /usr/local/bin/walletd &&     strip /usr/local/bin/simplewallet &&     strip /usr/local/bin/miner &&     strip /usr/local/bin/connectivity_tool &&     cd / &&     rm -rf /src/turtlecoin &&     apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev librocksdb-dev &&     apt-get autoremove -y &&     apt-get install -y        libboost-system1.58.0       libboost-filesystem1.58.0       libboost-thread1.58.0       libboost-date-time1.58.0       libboost-chrono1.58.0       libboost-regex1.58.0       libboost-serialization1.58.0       libboost-program-options1.58.0       libicu55' returned a non-zero code: 1```

**Comment by Svolentin** [comment]
```git checkout v0.3.0``` .. but it clones 0.2.2 :rofl:

**Comment by RocksteadyTC** [comment]
@michelangelo314

**Comment by michelangelo314** [comment]
fixed in #36

**Comment by Svolentin** [comment]
not fixed. if you download https://github.com/turtlecoin/turtlecoin/archive/v0.3.1.tar.gz you can see 0.3.0 in docker file.
