### ISSUE TITLE
simplewallet wont refresh if opened before turtleD is synced

### ISSUE THREAD

**Issue by BigslimVdub** [turtlecoin/turtlecoin#57]
TurtleD is sync then simplewallet opened, it refreshes fine. 

TurtleD is not sync then simplewallet opened, it states not connected to daemon and it keeps repeating even after TurtleD is sync. Have to close down simplewallet and reopen wallet and then it refreshes fine. 

windows 10 latest release

**Comment by Svolentin** [comment]
###
Also ```simplewallet``` does not see new transactions to your wallet if ```simplewallet``` launched after ```turtlecoind``` complete sync to latest block with network.

```simplewallet``` shows new transactions only if ```turtlecoind``` receive new blocks between two moments:
```turtlecoind``` starts sync, you see ```.. launch simplewallet ..```
you launched ```simplewallet``` and ```turtlecoind``` receive new blocks with your coins.

if you miss moment and launch ```simplewallet``` after ```turtlecoind``` get blocks with your coins you does not see them in balance.

Workaround: type ```reset``` in ```simplewallet``` cli to rescan the whole blockchain from zero.

### 
```simplewallet``` does not show your coins if blocks with them before highest bootstrap block
workaround: Don't use bootstrap blockchain. Remove all data from ```.TortleCoin``` folders (except your wallet file ofc)
Sync from scratch, wait until it say ```you can now launch simplewallet``` and launch ```simplewallet```, wait for blocks with your coins.

**Comment by BigslimVdub** [comment]
Everything works fine if turtleD is sync fully before opening simplewallet. 

What code was turtlecoin forked from Monero?

**Comment by thinkpol2** [comment]
@BigslimVdub  Could you please post the errors you're seeing and steps to reproduce this issue? 

I am unable to reproduce this issue with either method:

* Start turtlecoind, immediately run simplewallet without waiting for sync
-or-
* Run simplewallet, then start turtlecoind.

In both cases: errors are logged by simplewallet until turtlecoind is fully synced. Once synced, no indication is given by simplewallet but no more errors are logged. I am them able to send and receive TRTL without issue.

Tested on Windows 10 and Linux (TurtleCoin v0.3.2.1253 (0.1-g7fcc6ad)).

**Comment by BigslimVdub** [comment]
![0d93a8a0-c61a-4238-bdf0-630d5393b32f](https://user-images.githubusercontent.com/30030687/36499931-560d1db2-1708-11e8-9f25-5633cbe3b154.jpeg)

I let it run, however once a transaction came through from daemon it showed up and then showed the block sync as normal. If I had no incoming transaction it just keeps running the red error until I exit and reopen wallet when daemon is fully sync.

**Comment by ZedPea** [comment]
I'm not sure what this image is meant to be showing - your daemon isn't synced fully in this image, hence the "6 days behind"

**Comment by Svolentin** [comment]
fixed by change version in Dockerfile 0.3.0 to 0.3.2 and resync node.

**Comment by BigslimVdub** [comment]
ah yes, I am using 0.3.1

I will update to 0.3.2 and report back. I did not check to see there was an update.

**Comment by BigslimVdub** [comment]
Updated to 3.2 and simplewallet stops showing errors when daemon Is sync but it still shows every few seconds an error saying it’s not sync. So very annoying. Can we change the log intensity to only show this error once after starting simplewallet?
![34d38e75-8287-4809-b389-937c13af27c0](https://user-images.githubusercontent.com/30030687/36635236-47da95aa-1977-11e8-847a-90eaf5521454.jpeg)

**Comment by ereptor81** [comment]
This is fixed in master w/ simplewallet rewrite
